### ISSUE TITLE
Search shows less games when logged in

### ISSUE THREAD

**Issue by WillIForgetThis** [fapinstructor/fapinstructor-client#100]
To reproduce: 
- When not logged in, navigate to 'games' page and observe number of games at the bottom of the page
- Log in
- Navigate back to the 'games' page and observe number of games

Before logging in:
![image](https://user-images.githubusercontent.com/120166583/206650415-e656ccaa-7dff-4a18-9389-5344ab6abc49.png)

After logging in:
![image](https://user-images.githubusercontent.com/120166583/206650211-fb203090-d592-488a-82b0-ee11794b9407.png)

**Comment by FGBxRamel** [comment]
Closed due to development of version 2 (currently closed source).
