### ISSUE TITLE
Connecting to generic devices?

### ISSUE THREAD

**Issue by ghost** [fapinstructor/fapinstructor-client#97]
Hi,

Great project!

I've built my own sex-toy setup that uses MQTT to communicate with all kinds of things from vibrators and servos to heart rate monitors and magnetic locks.

I'd love to find a way to send the necessary messages from FI to my platform.

I've seen the Handy integration, I'm wondering if there's anything more that I need to do other than copy the [Handy directory](https://github.com/fapinstructor/fapinstructor-client/tree/main/src/features/handy) and make some changes there?

While I'm thinking about it, [buttplug.io](https://buttplug.io/) integration could be good for others as well?

**Comment by thefapinstructor** [comment]
Hey  @FurnitureFun!  That sounds like a really exciting idea.  I haven't looked at buttplug.io yet but definitely want to integrate it.  It might not be for a while since I'm busy but if you wanted to take a stab at it I'd be happy to review any PRs.

**Comment by thefapinstructor** [comment]
That seems actually quite easy to implement judging by that repo.  We can create a new file like handy.ts to handle the implementation details and we can use a modal window like handy to connect to the device.

**Comment by FGBxRamel** [comment]
Closed due to development of version 2 (currently closed source).
But it isn't forgotten, it will be transferred.^^
