### ISSUE TITLE
Attempting to "Share"/Save game results in 500 error

### ISSUE THREAD

**Issue by hiroaki-swords** [fapinstructor/fapinstructor-client#99]
![image](https://user-images.githubusercontent.com/119740810/205442661-2ec66a27-31b5-46a8-9282-e2b7c0b738ac.png)

To reproduce (above from Brave browser):
- Log in
- From Create Game screen, click "Share Game"
- Enter anything for name and tags
- Click Save Game

**Comment by FGBxRamel** [comment]
Closed due to development of version 2 (currently closed source).
And it should be long fixed.
